# Generated by Django 4.0.6 on 2022-07-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_alter_hotel_conformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='latitude',
            field=models.DecimalField(decimal_places=14, default=0.0, max_digits=16),
        ),
        migrations.AddField(
            model_name='hotel',
            name='longitude',
            field=models.DecimalField(decimal_places=14, default=0.0, max_digits=17),
        ),
    ]
