# Generated by Django 4.0.6 on 2022-07-08 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_hotel_latitude_hotel_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelsite',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.site'),
        ),
    ]
